[2020-08-10 09:45:41,922] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-10 09:46:46,070] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /monitor/api/server_monitor/history/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project_monitor/server_monitor/views.py", line 204, in get_history_monitor
    r = requests.get(settings.OPENTSDB_URL + "query?start=" + start_time + "&end_time=" + end_time + "&m=" + metric)
TypeError: can only concatenate str (not "NoneType") to str
[2020-08-10 09:46:46,074] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /monitor/api/server_monitor/history/?start=2020%2F08%2F07-07%3A00%3A00&end=2020%2F08%2F07-10%3A42%3A09&m=sum%3Atotal_percent HTTP/1.1" 500 19336
[2020-08-10 09:58:14,846] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-08-10 09:59:54,376] [log.py:222] [log:log_response] [WARNING]- Not Found: /monitor/api/v1/server_monitor
[2020-08-10 09:59:54,377] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /monitor/api/v1/server_monitor HTTP/1.1" 404 19264
[2020-08-10 10:00:01,044] [log.py:222] [log:log_response] [WARNING]- Not Found: /monitor/api/v1/server_monitor/
[2020-08-10 10:00:01,045] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /monitor/api/v1/server_monitor/ HTTP/1.1" 404 19267
[2020-08-10 10:00:04,674] [log.py:222] [log:log_response] [WARNING]- Not Found: /monitor/api/v1/server_monitor/1
[2020-08-10 10:00:04,675] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /monitor/api/v1/server_monitor/1 HTTP/1.1" 404 19270
[2020-08-10 10:02:00,982] [log.py:222] [log:log_response] [WARNING]- Not Found: /monitor/api/v1/server_monitor
[2020-08-10 10:02:00,983] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /monitor/api/v1/server_monitor?current_page=0&pre_page=10 HTTP/1.1" 404 19295
[2020-08-10 10:02:33,602] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /monitor/api/server_monitor?current_page=0&pre_page=10 HTTP/1.1" 301 0
[2020-08-10 10:02:35,073] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /monitor/api/server_monitor/?current_page=0&pre_page=10 HTTP/1.1" 200 32748
